In [2]:
import torch

torch.randint(0, 1, (1,))

tensor([0])

In [3]:
import numpy as np

array = np.array([1, 2, 3])
array[1:10]

array([2, 3])

In [5]:
frames = torch.zeros((1, 6))
a, b = frames.split((1, 5), dim=1)
a.shape

torch.Size([1, 1])

In [7]:
from einops import einops

tensor = torch.arange(9).view(1, 3, 3)
print(tensor)
tensor = einops.repeat(tensor, 't h w -> t (h hc) (w wc)', hc=2, wc=2)
print(tensor)

tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]])
tensor([[[0, 0, 1, 1, 2, 2],
         [0, 0, 1, 1, 2, 2],
         [3, 3, 4, 4, 5, 5],
         [3, 3, 4, 4, 5, 5],
         [6, 6, 7, 7, 8, 8],
         [6, 6, 7, 7, 8, 8]]])
